[versions]
agp = "8.3.1"
kotlin = "1.9.0"
coreKtx = "1.12.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.11.0"
activity = "1.9.0"
constraintlayout = "2.1.4"
rxjava = "2.2.21"
viewbindingpropertydelegateFull = "1.5.9"
dagger = "2.51.1"
daggerCompiler = "2.51.1"
retrofit = "2.11.0"
retrofit-adapter = "2.11.0"
converterGson = "2.11.0"
lifecycleViewmodelKtx = "2.7.0"
lifecycleLivedataKtx = "2.7.0"
parent = "3.14.9"
cicerone = "7.1"
room-runtime = "2.6.1"
room-compiler = "2.6.1"
room-rxjava2 = "2.6.1"
room-rxjava3 = "2.6.1"
hiltAndroid = "2.51.1"
hiltAndroidCompiler = "2.51.1"
rxandroid = "3.0.2"
hiltCompiler-version = "2.51.1"
hilt-android-version = "2.51.1"
mapsMobile = "4.6.1-navikit"
automotivenavigation = "4.6.1"
roadevents = "4.6.1"
search = "3.5.0"
compiler = "5.0.0-rc01"
glide = "5.0.0-rc01"
security = "1.1.0-alpha03"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

rxandroid = { group = "io.reactivex.rxjava3", name = "rxandroid", version.ref = "rxandroid" }
rxjava = { group = "io.reactivex.rxjava2", name = "rxjava", version.ref = "rxjava" }
viewbindingpropertydelegate-full = { group = "com.github.kirich1409", name = "viewbindingpropertydelegate-full", version.ref = "viewbindingpropertydelegateFull" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
adapter-rxjava3 = {group = "com.squareup.retrofit2", name = "adapter-rxjava3", version.ref = "retrofit-adapter" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converterGson" }
gson = {group = "com.google.code.gson", name = "gson", version = "2.10.1" }

androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }

hilt-android = {group = "com.google.dagger", name = "hilt-android", version.ref = "hilt-android-version" }
hilt-android-compiler = {group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltCompiler-version" }

circle-view={group="de.hdodenhof", name="circleimageview", version="3.1.0"}


parent = { group = "com.squareup.okhttp3", name = "parent", version.ref = "parent" }

cicerone = { group = "com.github.terrakok", name = "cicerone", version.ref = "cicerone" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room-runtime" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room-compiler" }
room-rxjava2 = { group = "androidx.room", name = "room-rxjava2", version.ref = "room-rxjava2" }
room-rxjava3 = { group = "androidx.room", name = "room-rxjava3", version.ref = "room-rxjava3" }
maps-mobile = { group = "com.yandex.android", name = "maps.mobile", version.ref = "mapsMobile" }
automotivenavigation = { group = "com.yandex.mapkit.styling", name = "automotivenavigation", version.ref = "automotivenavigation" }
roadevents = { group = "com.yandex.mapkit.styling", name = "roadevents", version.ref = "roadevents" }
search = { group = "com.yandex.android", name = "search", version.ref = "search" }
compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "compiler" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }

activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }

security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "security" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }